### PR TITLE
Fix missing libpython dependency on Windows

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
We should merge this in any case, but in order to reduce the number of published builds, let's wait to see if anything else comes out of #70 and #71...

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
@maresb I think this should be PRed into https://github.com/conda-forge/aesara-feedstock instead, no?

**Comment by maresb** [comment]
@twiecki, but there is not yet any dependency on aesara with PyMC3 v3.11.2. That would only be for future versions, right?

**Comment by twiecki** [comment]
Correct, I first would like to get aesara into the right state and then remove these things here.

**Comment by twiecki** [comment]
I suppose we can merge this here and then later remove it once we switched.

**Pull request merged**
