### PR TITLE
Increment to 3.3rc2

### PR DESCRIPTION
**Pull request by fonnesbeck**

### CODE REVIEW

**Comment by fonnesbeck** [comment]
Not sure what "batch file cannot be found" relates to?

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

@fonnesbeck the above re-rendering should work.

**Comment by fonnesbeck** [comment]
Not sure where these modified files came from

**Comment by ocefpaf** [comment]
@fonnesbeck the bot re-renders a recipe when we use the message "@conda-forge-admin, please rerender", see https://conda-forge.org/docs/webservice.html for more details.

However, something is amiss b/c it should not cause a conflict :unamused:

**Comment by fonnesbeck** [comment]
Is this good to merge despite the wait on the macOS builds? This is just a RC; we hope to get the release out shortly afterwards.

**Comment by ericmjl** [comment]
ping @ocefpaf @jakirkham is it okay to merge?

**Comment by ocefpaf** [comment]
With Travis-CI queue like that it is OK. You can watch OS X builds on master and fix it later if something is broken there.

PS: I enable Travis-CI on my account and then use that as a guide to merge b/c the my own queue is smaller than conda-forge's.

**Pull request merged**
