### PR TITLE
Bumping requirements to rc4

### PR DESCRIPTION
**Pull request by springcoil**

### CODE REVIEW

**Comment by ericmjl** [comment]
Bumping to rc3 or bumping to rc4? (The title of the PR, that is.)

Either way, once the checks finish, I'll push them up!

**Comment by springcoil** [comment]
Bumping to rc4

**Comment by twiecki** [comment]
```
bash: Miniconda3-latest-MacOSX-x86_64.sh: No such file or directory
/Users/travis/build.sh: line 62: /Users/travis/miniconda3/bin/activate: No such file or directory
/Users/travis/build.sh: line 63: conda: command not found
/Users/travis/build.sh: line 64: conda: command not found
/Users/travis/build.sh: line 65: conda: command not found
/Users/travis/build.sh: line 66: run_conda_forge_build_setup: No such file or directory
The command "MINICONDA_URL="http://repo.continuum.io/miniconda"
  MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
  curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
  bash $MINICONDA_FILE -b
  
  source /Users/travis/miniconda3/bin/activate root
  conda config --add channels conda-forge
  conda config --set show_channel_urls true
  conda install --yes --quiet conda-forge-build-setup
  source run_conda_forge_build_setup
  " failed and exited with 1 during .
Your build has been stopped.
```

**Comment by ocefpaf** [comment]
@twiecki you need to rerender the feedstock. Are you familiar with `conda-smithy`?

**Comment by twiecki** [comment]
Not familiar, what does it entail?

**Comment by ocefpaf** [comment]
@twiecki to force me to write better docs I just created

https://github.com/conda-forge/staged-recipes/wiki/conda-smithy-rerender

Please help me with some feedback so I can improve it.

**Comment by springcoil** [comment]
I've pushed those changes based on your tutorial @ocefpaf

**Comment by springcoil** [comment]
That didn't work. I'll try again.

**Comment by ocefpaf** [comment]
> That didn't work. I'll try again.

It looks OK to me. Maybe you rebased and I missed something. If Travis-CI passes this is good to go.

**Comment by springcoil** [comment]
Ok cool

**Comment by springcoil** [comment]
It looks like it works - can you merge this in @ocefpaf ?
cc @twiecki

**Comment by twiecki** [comment]
Thanks @springcoil and @ocefpaf. @ocefpaf when will this be available on conda-forge?

**Comment by ocefpaf** [comment]
> @ocefpaf when will this be available on conda-forge?

As soon as the CIs finish:

https://circleci.com/gh/conda-forge/pymc3-feedstock/11

https://ci.appveyor.com/project/conda-forge/pymc3-feedstock/branch/master

https://travis-ci.org/conda-forge/pymc3-feedstock/builds/181633376

**Pull request merged**
