### PR TITLE
3.1rc3

### PR DESCRIPTION
**Pull request by ericmjl**
also changed to sha256

### CODE REVIEW

**Comment by jakirkham** [comment]
Might be good to squash the commit history.

**Comment by ericmjl** [comment]
@jakirkham is squashing necessary?

**Comment by ericmjl** [comment]
ping @twiecki: just merged.

**Comment by jakirkham** [comment]
> is squashing necessary?

No, just a friendly suggestion. 😄

**Comment by twiecki** [comment]
Thanks!

**Pull request merged**
