### PR TITLE
Prepare for rc releases

### PR DESCRIPTION
**Pull request by jakirkham**
Change the upload location to use the `rc` label on the `conda-forge` channel when uploading packages.

### CODE REVIEW

**Comment by jakirkham** [comment]
This is the next step @ericmjl. Please merge when it passes.

**Comment by ericmjl** [comment]
Ah, I think I understand the changes seen here.

ping @twiecki and @fonnesbeck, it's going to be merged!!!

**Comment by jakirkham** [comment]
Thanks @ericmjl. Glad it makes sense.

**Comment by twiecki** [comment]
Thanks! How can a user install this? I see there's a new `rc`channel.

**Comment by jakirkham** [comment]
Yeah, I really dislike that this happens. It is some bug that probably originates with Anaconda, but have it on the upload script for now.

xref: https://github.com/conda-forge/conda-forge-build-setup-feedstock/issues/41

**Comment by jakirkham** [comment]
As far as how to download `rc` releases, one does `conda install -c conda-forge/rc pymc3` to do this. Would note that this may pull in other `rc` packages too. So please make sure to check what `conda` is installing and verify that it is ok before proceeding.

**Pull request merged**
