### PR TITLE
Updated version to 3.5.rc1

### PR DESCRIPTION
**Pull request by fonnesbeck**

### CODE REVIEW

**Comment by ericmjl** [comment]
Help @ocefpaf! I'm not sure what's going wrong here. The recipe has the correct SHA256 for the tarball, but it looks like the CIs are pulling down the wrong version (3.4 rather than 3.5rc1). Is there something we can do to make it right?

**Comment by ocefpaf** [comment]
Sorry @ericmjl, still trying to catch up with the backlog after SciPy. I'll take a look at this in a moment. (GitHub releases changes checksum if something in the release changes and maybe we only need to update it.)

**Comment by ocefpaf** [comment]
@ericmjl the updated sha256 seems OK. Just bare in mind that, if the release info is changed after the CIs are green we may still get a broken CI on master due to the changed sha256. I recommend PyPI tarballs, or even GitHub uploaded tarballs, to avoid that. (Or don't edit the release info after publishing it :wink:)

**Comment by ericmjl** [comment]
Hooray! Thanks @ocefpaf for the info!

**Comment by ericmjl** [comment]
cc @fonnesbeck

**Pull request merged**
