### PR TITLE
3.1rc2

### PR DESCRIPTION
**Pull request by ericmjl**
version bump to 3.1rc1. This time using GitHub source rather than PyPI. Hope I didn’t mess it up!

### CODE REVIEW

**Comment by twiecki** [comment]
`error: package directory 'docs' does not exist` @fonnesbeck the file you uploaded to pypi is missing the docs directory

**Comment by ericmjl** [comment]
@fonnesbeck waiting on a new upload!

**Comment by fonnesbeck** [comment]
@ericmjl I'm waiting to have a PR merged before I can create a new one.

**Comment by twiecki** [comment]
@fonnesbeck PR is merged. we might have to cut a new release though.

**Comment by fonnesbeck** [comment]
Will tag one now.

**Comment by fonnesbeck** [comment]
3.1.rc2 should be available on PyPI now.

**Comment by jakirkham** [comment]
This package is a dev release and will require a dev release of `theano`. Except one discussion around `ipympl`, I don't know of any packages that have been dev releases and required a package that was a dev release. How do we feel about this, @conda-forge/core? Personally I'm ok with it as long as they are both under the dev label and not in main?

xref: https://github.com/conda-forge/staged-recipes/pull/1118

**Comment by fonnesbeck** [comment]
@jakirkham our intention is to hold off on releasing 3.1 until Theano 0.9 is released.

**Comment by twiecki** [comment]
Exactly, just want to iron out any issues before.

**Comment by ericmjl** [comment]
@twiecki @fonnesbeck so to clarify, do you guys want to release RC2 on to conda-forge?

**Comment by twiecki** [comment]
@ericmjl Yes, but mainly for testing purposes.

**Comment by ericmjl** [comment]
ping @jakirkham what's the best route for this?

**Comment by jakirkham** [comment]
As noted, personally I'm ok with this given some tweaks (which I can advise on), but was trying to open the floor to other core members to share their opinions.

**Comment by ericmjl** [comment]
@jakirkham noted! Thanks for the input; hope the rest of @conda-forge/core can weigh in!

**Comment by twiecki** [comment]
Theano 0.9.0 was just released, so we can just depend on those once they are built.

**Comment by ericmjl** [comment]
ping @jakirkham @ocefpaf I am having trouble restarting CircleCI. Could you help me restart the build please?

**Comment by ericmjl** [comment]
ping @ocefpaf @jakirkham all tests pass, I am going to merge! Just want to check that it's all okay?

**Comment by jakirkham** [comment]
It needs to be uploaded with an `rc` label. Can help in a couple of days, but am otherwise engaged ATM.

**Comment by jakirkham** [comment]
First step is just to get things re-rendered. Please see PR ( https://github.com/conda-forge/pymc3-feedstock/pull/13 ) for that.

**Comment by ericmjl** [comment]
@jakirkham I've already re-rendered with 2.2.2. See fe6699e for that.

**Comment by jakirkham** [comment]
I've updated the base branch from `master` to `rc`. There may be some conflicts. Please resolve these conflicts locally and push the changes when you have a chance, @ericmjl.

**Comment by jakirkham** [comment]
Thanks @ericmjl. Merging this should release it to the `rc` channel.

Subsequent RC versions can be PR'd to the `rc` branch as well. Once a stable release is made that can be PR'd to `master.

Hope that helps.

**Comment by jakirkham** [comment]
Appears to be passing.

**Comment by ericmjl** [comment]
Merged!

**Comment by twiecki** [comment]
conda install -c conda-forge/rc pymc3 github.com/pymc-devs/pymc

```
Fetching package metadata ....
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/conda-forge/rc

It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.

If the requested url is in fact a valid conda channel, please request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
.......


PackageNotFoundError: Package not found: Conda could not find '
```

**Comment by ericmjl** [comment]
Do `conda install -c conda-forge/label/rc pymc3`.

**Pull request merged**
