### PR TITLE
MNT: Re-rendered with conda-smithy 2.2.2 [ci skip]

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by jakirkham** [comment]
Strange. Travis CI didn't start. 😕

**Comment by ericmjl** [comment]
@jakirkham: sorry! I should have made my PR title clearer, it's already been re-rendered with 2.2.2 in #12.

**Comment by jakirkham** [comment]
So we need this as part of creating the `rc` branch. This will need to be done before that PR goes in anyways. It is only the first step of creating that branch.

**Comment by ericmjl** [comment]
Okay, got it. So should I close the other PR then?

**Comment by jakirkham** [comment]
No it can stay open. We will redirect it to the `rc` branch once it is ready. There will be another PR after this one to configure the `rc` branch.

**Pull request merged**
