### PR TITLE
Rebuild 3.8 to fix missing geweke import

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Fixes https://discourse.pymc.io/t/6818

I'd like to rebuild the following versions in order to add `arviz<0.11.2` in order to resolve the `geweke` module problem.

* [X] v3.8
* [ ] v3.9.1
* [ ] v3.9.2
* [ ] v3.9.3
* [ ] v3.10.0

We may want to do this in a separate branch in order to keep master clean. I can't create a new branch myself since I'm not a maintainer on this feedstock.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
I think I probably didn't explain so precisely what my intentions are...

There is a problem with the feedstocks from `v3.8` to `v3.10.0` inclusive, relating to how `pymc3` depends on `arviz`. The problem is that `v0.11.2` of `arviz` removed `arviz.geweke`. Unfortunately, the aforementioned `pymc3` versions import this module on initialization. This means that `pymc3` will be completely broken. The command `import pymc3` will fail.

Now let's say I run `mamba install -c conda-forge pymc3==3.10.10`. Then `mamba` will install that version of `pymc3`, plus the latest "compatible" versions of its dependencies. Namely, it will install a new version of `arviz` which is missing `geweke`.

I propose to fix this problem by sequentially revising the affected builds to include an upper limit on the `arviz` version, namely `<0.11.2`.

This PR is the first step of this process, namely rebuilding `v3.8`. Here are [the relevant changes to `meta.yaml` for this PR from the original 3.8 version](https://github.com/conda-forge/pymc3-feedstock/compare/4bf34d2..dc00cd8#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9a).

**Comment by maresb** [comment]
The problematic commit to `arviz`: https://github.com/arviz-devs/arviz/pull/1545

**Comment by ericmjl** [comment]
Thanks @maresb! Things look good on the CI. I'm going to get one more input from either @OriolAbril or @canyon289 just to make sure things are okay. Though I'm a maintainer on the feedstock, I haven't been involved enough in the day-to-day development of ArviZ to know whether there are hidden warts to look out for.

**Comment by maresb** [comment]
@ericmjl, sounds good.

Also, in case there are any other outstanding issues with those builds, now may be a good time to address them. :wink:

**Comment by OriolAbril** [comment]
This is great, thanks! I don't know about any other issues relating those builds, all the posts complaining about geweke on discourse seem to have been solved with that instead of running into other problems

**Comment by ericmjl** [comment]
Okie dokes, @OriolAbril and @maresb. I'm going to merge, let's see if there are any other issues that crop up!

**Pull request merged**
